"""Document types for agent file outputs with path tracking."""

from typing import List, Optional
from pydantic import BaseModel, Field


class DocumentT(BaseModel):
    """A document with path and explanation"""
    path: str = Field(description="File path of the generated document (relative to working directory)")
    explanation: str = Field(description="Explanation of what the document contains")
    absolute_path: Optional[str] = Field(default=None, description="Absolute file path (populated by post-processing hook)")


class DocumentsT(BaseModel):
    """Collection of documents generated by an agent"""
    documents: List[DocumentT] = Field(description="List of documents generated")